### ISSUE TITLE
Possible issue with timezones?

### ISSUE THREAD

**Issue by martinpaljak** [SeaPea/GentleWake#12]
Hello (and thanks for the great software).
I use GW and love it - it is a "set and forget" kind of software, which is ideal for a smartwatch.

Today I slept in, either because I was really tired, or the alarm went off at incorrect time. I have an alarm set for 7.20 with 30m alert time, which usually wakes me up around 7am. I had a travel yesterday from current timezone -1H, but when the phone picked up the local time, all seemed good. I checked in the evening, that alarms are on and next is scheduled for 7.20 tomorrow morning. All good.

But the alarm I noticed, was at 8.02 today morning, so either I slept for 1 hour without noticing the vibration, or the alarm was off by one hour. Could it be that some kind of timer, if set in a previous timezone, does not get updated properly?

Any thoughts?

**Comment by SeaPea** [comment]
Unfortunately the Pebble OS does not let apps know when the time has changed due to crossing time zones (there is a kludge to try and deal with DST changes) and the wake up event in the OS that is used to activate the alarm is set in UTC time. Hence after the last alarm or last time you go into the GW settings the next alarm is set to the same time zone. There is no way of fixing this as far as anyone knows. The best thing you can do is go into GW after changing time zones and use the top right button to toggle alarms off and on. That will reset the alarms for the current time zone although it will also reset the one time alarm if that had been set.

**Comment by martinpaljak** [comment]
Okay. Thanks for the tip, the enable-disable cycle seems like a good enough fix for now.
