### ISSUE TITLE
"Get out of bed" code

### ISSUE THREAD

**Issue by bharrisau** [SeaPea/GentleWake#6]
The Konami code is great (as is the watchapp). I'm suggesting a harder mode where the app asks for a code that has been printed on paper. Then I can leave the paper in the bathroom or kitchen and have to get out of bed to turn the alarm off.

The printed card could just have 10 rows and 10 columns with the button to press, and the app asks for a row and to start at a certain column. The person then enters the 5 buttons going across the row.

The mode would need to be hidden so only people with the pdf/picture could activate it (to avoid confusion)

**Comment by SeaPea** [comment]
Interesting idea. 

I was thinking about adding a feature of a second alarm that will automatically activate if it doesn't look like the wearer has got out of bed. 

The way I was thinking about doing this though is the let the user specify which arm they wear the watch on (or just turn the second alarm off) and then it could use the accelerometer to detect if the wearer has stood up with arms hanging down mostly and moved around a bit. I don't want to make this too complicated though since it has already reached the max size of app for the original Pebbles.

**Comment by SeaPea** [comment]
Added a Get Out Of Bed alarm a while ago, which seems to work for most people, as described above. Doesn't need to specify which arm the watch is on.
