### ISSUE TITLE
Re-use of Health sleep status?

### ISSUE THREAD

**Issue by martinpaljak** [SeaPea/GentleWake#7]
With a PTS, I find that the sleep tracking information is quite accurate. Is it possible to re-use this information? For example:
- have a profile for weekends, that wakes me up "not before I've had the minimal/optimal" amount of sleep, according to Health (or just a fixed time), but "not after a set time".
- if I wake up before wakeup time, currently the alarm goes off at the beginning of the gentle wake period, but I'd like to make it go off at the alarm time instead (just to remind me that "you need to get to dressed now")

Probably a generic thing with Pebble as a platform, I'd expect to be able to share common events much more easily.

**Comment by SeaPea** [comment]
While Pebble are adding API access to the health data in 3.9 there are no events or triggers that would start an app based on when someone falls asleep or wakes up. So Gentle Wake would have to run using the background activity slot and frequently poll the health data to find out when it thinks you fell asleep and when you wake. This would use up a lot of the battery, so I don't think this will be feasible. One of the primary goals of Gentle Wake is to use very little power. Detecting someone falling asleep and waking up also isn't necessarily an instantaneous event as it has to look over several minutes to analyze what is going on since it only has your arm movements to work make an educated guess as to whether you are awake or asleep. So I'm not sure if it would have access to your waking state in a timely enough manner for the alarm. 

I am however, thinking about adding an optional second alarm that activates if it doesn't look like you have got out of bed (using movement) after dismissing the alarm.

**Comment by martinpaljak** [comment]
It is more likely a request to Pebble for platform/API improvements than for Gentle Wake. It is great that GW is with open source but unfortunately I've not yet had time to actually build anything or otherwise get a better grasp on the API, to know what would be possible and what is not.

The atmosphere in smartwatch area should be competitive, I'd expect the API to be a (fast) moving target and providing more intelligent and coherent sensory/state/event information to applications with minimal battery cost (what is my main reason for a PTS) should be a top priority for Pebble.

As a current Pebble developer, where would you suggest to be the best way to get involved with such discussions?

And thanks for the great app that indeed is a "fire and forget" solution and "does what I mean" :)

**Comment by SeaPea** [comment]
There's the Pebble forums where developers still comment:
[https://forums.getpebble.com/categories/developer-discussion](https://forums.getpebble.com/categories/developer-discussion)
I haven't used it but apparently Slack is a popular discussion area too:
[http://slack.pbldev.io](http://slack.pbldev.io)
You can also submit suggestions directly to Pebble through the Pebble phone app under the Support tab or here: [http://pages.getpebble.com/pages/suggestions](http://pages.getpebble.com/pages/suggestions)
